Add server
shukal94/commercehall pull request #1
Opened 2019-04-10 14:19 UTC by Fln1k

2019-04-10 14:26 UTC, shukal94 requested changes
In this repository we don't need at all. Reason: I'm not going to change your own virtualenv and pycharm and pycache files, we need only source code. 
Suggest to customize `.gitignore` file

2019-04-10 14:43 UTC, shukal94 requested changes
you have a GOD endpoint there, not a good practice

2019-04-10 14:43 UTC, shukal94 commented on main.py
> +    img.save('Схема.png')
In future, try to avoid Cyrillic codecs, servers where you going to deploy might be not support russian locale

2019-04-10 14:43 UTC, shukal94 commented on main.py
> +def make_matrix():
which matrix?

2019-04-10 14:43 UTC, shukal94 commented on main.py
> +    a = request.json
you can try `a = request.get_json()`
and what is `a`

2019-04-10 14:43 UTC, shukal94 commented on main.py
> +    dict = {'Not_Available': 'red', 'Available': 'green', 'Cashbox': 'yellow', 'Rack': 'blue'}
1) `dict` - reserved python identifier, choose other name,
2) could you please move states dictionary into another place, more global?

2019-04-10 14:43 UTC, shukal94 commented on main.py
> +    img = Image.new('RGB', (1400, 1000), color='white')
remove hardcode

2019-04-10 14:43 UTC, shukal94 commented on main.py
> +    pointer_y = 0
pointer translates as `указатель`

2019-04-10 14:43 UTC, shukal94 commented on main.py
> +    draw = ImageDraw.Draw(img)
please move image processing logic into another place

2019-04-11 05:54 UTC, Fln1k commented on main.py
> +    pointer_y = 0
указатель по x, указатель по y. what's wrong?

2019-04-11 13:24 UTC, shukal94 commented on main.py
> +    state_dictionary = {'Not_Available': 'red',
you can place state dict outside of any functions, it's constant so you'll don't need to pass whis as parameter

2019-04-16 06:24 UTC, shukal94 approved these changes

2019-04-16 06:24 UTC, merged